### ISSUE TITLE
感谢明哥！

### ISSUE THREAD

**Issue by Relsoul** [drduan/minggeJS#101]
我觉得好不好应该由学习人员来说，因为一个库是让大众，让小白用着舒服，用着放心。所以库好不好完全是由大众来评测的，身为大众中的小白人员更要来评测了.
从小妈妈,哦不对,是大家都叫我,学习JS一定要学习jquery,因为他方便,封装了Dom操作,Ajax,Animate..常用的操作，使JS变得简单,使Ajax操作触手可及,使Dom操作变得像每晚上撸*一样,一切都是那么顺手。
本来嘛，学习个jquery库就行了,突然大家又说,jquery源码一定要读，评价一个前端开发人员的标准就是能否读完读懂j！q！u！e！r！y！源码,什么玩意,学个jquery还要去看源码,再说jquery源码好多的奇淫技巧，学这货做什么，我能从源码中学到啥？什么工厂模式，原型链，继承，重载，浏览器功能性判断,队列控制，这些都是jquery源码写的！什么玩意！学这些有个啥用。
突然有一天,我无意中遇到了一个完美的库，她像jquery却比jquery长得更漂亮，那36D丰满的胸部一开就不像是隆德，那倾城倾国的容颜一看就不是整的，jquery在她面前什！么！都！不！是！
她就是大名鼎鼎的minggeJS！！你无法想象她有多优雅，jquery能做的她都能做！她用了一个星期！一个星期就出现在我的眼前，没有一点点准备，你就这样悄然无息的出现在我眼前，出现在我心中！她比jquery瘦3倍！jquery重160kb,她！她仅仅重40kb！对！多么优雅的身躯，让我柔柔一握那她小蛮腰！多么完美！
我看了她的源代码！多么优雅，多么精简，没有设计模式，没有繁杂代码！她的一切我都看得懂！看得清清楚楚一清二白！我哭了！这么精简优雅的库为什么这个时候才出现在我眼前，我想起了往日的坚信，我想起的夕阳下我和jquery的奔跑.我抹抹眼泪.我开始使用她! 我用她完成了前端最不可能完成的任务！做一段动画！So Beautiful！ 动画,是用CSS3精心打造的,她不仅仅支持chrome,而且还支持火狐,360浏览器,QQ浏览器,遨游浏览器,2345浏览器,就连IE10 她也是用CSS3实现支持的！ 而jquery呢？愚昧无知的jquery还在用队列来实现IE6,7，8，9的兼容！ 愚昧！这些浏览器也就家里那年老的父母用,父母不懂装浏览器,只会用那自带的IE浏览器,他们用的还是8,9代. 当我们想给父母发一段祝贺WEB时! 我们要让父母用上chrome浏览器 用上最好的浏览器 没有了minggeJS 我想,我的父母永远都不可能用上chrome浏览器 感谢minggeJS！
minggeJS! 不山寨jquery,只让jquery山寨, 而作者的发言也让我感到热血！激情澎湃！
我给了他一个霸气的名字：MingGeJs，
MingGeJs是什么？它是我一个星期完成的作品，它是一个JS类库，它拥有和JQUERY相同的语法，相同函数，相同的函数用法， 但是动画，选择器性能，函数 效率都在JQ之上，同时兼容IE 6 7 8，同时与JQUERY相兼容
它的名字叫MingGeJs，MingGe就是我的大名， 一看到插件名字，就知道作者是我，知道它是国产的，让别人知道国产类库一样做得很出色，出众
本人文化程度不高，初中毕业！半句英文都不会，但是我相信只要肯努力一样可以实现自己的梦想。MingGeJS的梦想有点大胆，就是在全球范围内，占据
JQUERY百分之50以上的用户份额
霸气的发言,让我感觉到乡村那浓浓的贵族味道！啊！这就是贵族的味道!
感谢MingGeJs！感谢作者,让我回到了激情燃烧的岁月

**Comment by lwbjing** [comment]
你妹啊，，把我看哭了。。

**Comment by luckyadam** [comment]
**MingGeJs** 请拼对，好么

**Comment by rindybo** [comment]
大神 666

**Comment by minggeJS** [comment]
这种带骨的文章，以后一律不回，不排除删贴处理
