### ISSUE TITLE
Please use English in github

### ISSUE THREAD

**Issue by Hackerline** [drduan/minggeJS#11]
Why you guys always use Chinese in github?
PS:Some people even do not has the qualification to abuse others

统一回复下。
我认为github上不仅仅是中国人，我们就应该用英文来交流，方便所有人来交流。
有些脑子有包的人认为我是装逼。
第一，我英语并不好，我装逼为什么要选自己不了解的领域？
第二，我本身是个非常讨厌装逼的人。
我只是随意说说，有几个说我装逼的，我也不知道哪里让你觉得了。
如果你非要说我装逼，那我只能说，我操你妈。哈哈
个人理解不同，别不了解我的想法就给我瞎扣帽子。
我还觉着你骂我装逼就是旨在说明自己英语好呢，是一种装逼于无形的手法，你怎么解释？
喜欢装逼的人，看谁都是在装逼。
--------------------------------------------------
关于我那个KWSD之前README用中文的。
那个是我两年前的项目，当时没有这个意识。
前阵子在一个项目下面看到有人用中文提issue然后别人要求他改成用英文，我才有的感触。
所以我虽然英语不好提个英文issue错误百出。
包括这里speak English  say Chinese也充分证明我把英语还给了老师。
@hoosin 同学一个劲嘲讽我装逼我也是没看懂。

**Comment by xqin** [comment]
https://github.com/Hackerline/KWSD

@Hackerline  敢问你的English呢?
而且你没看楼主的`README.md`吗? 
```
本人文化程度不高，初中毕业！半句英文都不会，但是我相信只要肯努力一样可以实现自己的梦想。MingGeJS的梦想有点大胆，就是在全球范围内，占据
```

**Comment by qusiba** [comment]
say Chinese? 
这里应该是用 speak 吧。
因为作者是中国人，提 Issues 和 PR 是可以用中文的。

**Comment by minggeJS** [comment]
I can't speak English,Please use Chinese

**Comment by meowtec** [comment]
@qusiba 
I don't think so. The author has said '占据JQUERY百分之50以上的用户份额',  It means that mingge.js will be used by many LaoWais. LaiWais can not read Chinese. So I hold the opinion that README should be written with English.

**Comment by egoist** [comment]
这个我就得资持一下明哥了，说不说英语是取决于一个项目和这个项目的作者的，为什么要在一个 README 全是中文，注释也是中文的项目里说英文?

说英文是为了开发者和使用者方便，而不是装逼呢！

---

P.S. 不过明哥这个项目不是放眼全球吗，和 jQuery 抢份额吗，用英文搞 README 和文档好点呢！是吧明哥！

**Comment by xqin** [comment]
`LaiWais` ? @meowtec 

既然中国人可以学英文, 为什么外国人不可以学中文?

**Comment by egoist** [comment]
@xqin 一个命题不和它的逆命题等价，而是和逆否命题等价。

**Comment by Hackerline** [comment]
'say English'  I made a mistake.....: (

**Comment by Hackerline** [comment]
@xqin Oh,this project has been commited two years ago.I will fix it.

**Comment by wtdragon** [comment]
haha~~

**Comment by code-artisan** [comment]
装逼不成倒打一次脸 :smile:

**Comment by justjavac** [comment]
开源界就需要明哥这样的人，明哥不需要英语。

> 老实说我从来没用过英语，正因为我反感英语。 为什么我反感，因为我完全有创造英语的能力，英语的语法我都了如指掌。 我要自己创建一门语言。
> 
> 它的名字叫MingGe语，MingGe就是我的大名， 一看到语言的名字，就知道作者是我，知道它是国产的，让别人知道国产语言一样做得很出色，出众

**Comment by Hackerline** [comment]
@code-artisan I just want to say something useful

**Comment by laolai** [comment]
哈哈哈 装逼被二楼打脸赶紧在28分钟前提交了一个更新，楼主你真是装逼界的楷模

**Comment by code-artisan** [comment]
俺是中国人，对俺说话请说中文，谢谢！

**Comment by Hackerline** [comment]
@laolai 为什么你看到的就是装逼？我只是说明一个事实。
我已经在好多issue里看到说中文然后被国外人喷了。
有意思？
不用英文是因为我并不会用英文喷人

**Comment by Hackerline** [comment]
@laolai 英语差就不能说？笑

**Comment by hoosin** [comment]
@Hackerline 打狗看主人，repo owner 是老外，你去提中文 issues 不是找抽么？有可比么？

该用英语的时候不用英语，不该用英文的时候又装逼。

You were plain touch the tender spot.

**Comment by jsonxu** [comment]
Brother Ming JS.

**Comment by Hackerline** [comment]
@hoosin 哦，我觉着不论repo owner是不是中国人，既然在github上，当然大家都应该说通用语，难道国外人看不到这个么？
我觉着大家都应该说英文就是装逼了？
我是要故意秀自己的英文水平？
我英语并不好，并没有秀的必要。
如果你觉着我是装逼，那就这么认为吧。
还有你这句“该用英语的时候不用英语，不该用英文的时候又装逼”，前半句我貌似并没有这样过？信口开河？
你开心就好 :)

**Comment by Hackerline** [comment]
统一回复下。
我认为github上不仅仅是中国人，我们就应该用英文来交流，方便所有人来交流。
有些脑子有包的人认为我是装逼。
第一，我英语并不好，我装逼为什么要选自己不了解的领域？
第二，我本身是个非常讨厌装逼的人。
我只是随意说说，有几个说我装逼的，我也不知道哪里让你觉得了。
如果你非要说我装逼，那我只能说，我操你妈。哈哈
个人理解不同，别不了解我的想法就给我瞎扣帽子。
我还觉着你骂我装逼就是旨在说明自己英语好呢，是一种装逼于无形的手法，你怎么解释？
喜欢装逼的人，看谁都是在装逼。

**Comment by hoosin** [comment]
@Hackerline 『通用语』，Github规定的？

别人家的老婆真的比你老婆好？

>  如果你非要说我装逼，那我只能说，我操你妈。哈哈

就你这素质还来 Github

**Comment by qusiba** [comment]
@Hackerline 你是对的，提 Issue 有时候也要考虑使用项目然后跟你遇到一样问题的人来搜索 Issue 列表，这个时候不管项目作者是不是用英文，最好用英文提 Issue，不过在这个项目，这种可能性不大。

人身攻击就看不下去了，我也看不出 @Hackerline 有装逼的意图。他的话也有道理，也许明哥不应该这么狂，但是比起一些不懂得尊重别人的人来说，明哥好太多了。

**Comment by Hackerline** [comment]
@hoosin github只能素质高才能上吗？毕竟我不是圣母，我也只是个会说脏话素质低的程序员而已。
全球通用语是英语，这个需要规定吗？

**Comment by Hackerline** [comment]
@hoosin github不是程序员社区吗？什么时候不能说脏话了？

**Comment by kuixiansheng** [comment]
在联合国的所有会议、官方文件，以及有关记录、事务中可以使用的语言称为联合国工作语言，联合国的工作语言共有6种：汉语、英语、法语、俄语、阿拉伯语与西班牙语。

**Comment by hoosin** [comment]
@kuixiansheng excellent！

**Comment by egoist** [comment]
@Hackerline GitHub is not Quora...

**Comment by hoosin** [comment]
@egoist The wealth of the mind is the only wealth.

**Comment by xiaowei1118** [comment]
老实说我从来没用过英语，正因为我反感英语。 为什么我反感，因为我完全有创造英语的能力，英语的语法我都了如指掌。 我要自己创建一门语言。

它的名字叫MingGe语，MingGe就是我的大名， 一看到语言的名字，就知道作者是我，知道它是国产的，让别人知道国产语言一样做得很出色，出众

**Comment by otarim** [comment]
@hoosin 头像狠帅气！

**Comment by xiaowei1118** [comment]
明哥我粉你了，快粉我一下，粉我一下

**Comment by hoosin** [comment]
首先我觉得开这个 issues 就是在自讽，如果你认为有必要用英语，自行翻译贴出去就好了，没必要教育别人该咋做，自己 『readme.en.md』 发个 PR 来  ，比啥都强，提这个 issues 有 Java（8）用 !

**Comment by hoosin** [comment]
或者你想来个岛国版的 『readme.jp.md』我也会帮你 Merge  ：)

**Comment by choleraehyq** [comment]
你自己那个KWSD被打脸之后赶紧发了个commit，结果内容是bullshit，你这才是地道的丢人。
本来你中文老外还看不懂，现在改成英文了结果是bullshit，老外怎么想？

**Comment by targetkiller** [comment]
围观。。

**Comment by xuexb** [comment]
我是来膜拜 @justjavac  哥的～

**Comment by xiaonianji** [comment]
围观露脸

**Comment by Hackerline** [comment]
@choleraehyq 
我只是提议下。看到有人说我的项目用的是中文我立马改过来，并不是想掩饰什么，只是觉着他说的有理，我确实需要改成英文的。
至于老外看了怎么想，和我有什么关系，那个KWSD本来就是bullshit。我只是在评论自己的项目而已
而且那个项目是两年前大二的暑假作业，我就传上来备个份。
即使我自己被打脸了，我还是提议大家都用英文来提issue。

**Comment by Hackerline** [comment]
@hoosin 我没有想要教育别人怎么样。我只是提议而已。当然你可以不接受。
但是你一直嘲讽我是几个意思？
能不能正常讨论问题？

**Comment by hiwanz** [comment]
huo qian liu ming.

**Comment by YeomanCai** [comment]
6666666

**Comment by CodeFalling** [comment]
@Hackerline 
> github 不是程序员社区吗？什么时候不能说脏话了?

https://help.github.com/articles/github-terms-of-service/#g-general-conditions
> Verbal, physical, written or other abuse (including threats of abuse or retribution) of any GitHub customer, employee, member, or officer will result in immediate account termination.

倡议使用英文我赞同，但

>  github 只能素质高才能上吗？

![report](https://cloud.githubusercontent.com/assets/391331/8244571/3ad2a9b6-15d7-11e5-9309-b13abd05ac01.png)

**Comment by Hackerline** [comment]
@CodeFalling  确实语言过激了  以后注意。多谢指点

**Comment by hoosin** [comment]
@Hackerline 

我哪有冷嘲热讽，我在最后不过是在和你讨论 JAVA8 而已。 ：）

以后你的 Repo ， PR 『readme.zh.md』，你会帮我 Merge 么？ 

逃：（

**Comment by Hackerline** [comment]
@hoosin 你开心就好

**Comment by jsonxu** [comment]
你再怎么有理，爆粗口你就输了。

**Comment by dstollie** [comment]
Though I love the idea of recreating jQuery in a better way. I dont understand why The ambition is to take over jQuery if like everything besides The special readme is written in Chinese. This project does nog give me any good feeling to use if The whole community besides it only talks Chinese... Even The documentation (where there is), is written in chinese. Is this only my weird opinion or do you guys have a different view about this?
