### ISSUE TITLE
我是minggeJS,一齐都是炒作团队，

### ISSUE THREAD

**Issue by minggeJS** [drduan/minggeJS#144]
![qq 20151216174929](https://cloud.githubusercontent.com/assets/16284765/11837895/9960c76c-a41e-11e5-8ee2-5c6adc94db8e.png)

**Comment by importcjj** [comment]
火钳刘明

**Comment by cdll** [comment]
前排花生瓜子儿～

**Comment by booxood** [comment]
前排?

**Comment by minggeJS** [comment]
整个炒作装逼事件的主谋就是他，软文他写，让我装逼说会火起，于是信了，可是我太单纯信错他的

**Comment by a578242325** [comment]
66666666666

**Comment by enjoydegame** [comment]
的确是火了

**Comment by minggeJS** [comment]
![Uploading QQ图片20151216171950.png…]()

**Comment by minggeJS** [comment]
有事找他，大家不要关注我了，他是千夫所指，万物所视，把目标转移到他，炒作团伙的主谋

**Comment by XadillaX** [comment]
> [Uploading QQ图片20151216171950.png…]()

是 shenmegui😂

**Comment by a578242325** [comment]
明哥不给力ia 图片还不会发

**Comment by minggeJS** [comment]
关注minggeJS，无限欢迎，关注我的话，不必了

**Comment by minggeJS** [comment]
认住他的帐号，整个装逼炒作的核心人物

**Comment by minggeJS** [comment]
![Uploading QQ图片20151216171950.png…]()
![Uploading QQ图片20151216171950.png…]()

**Comment by minggeJS** [comment]
111111111

**Comment by justjavac** [comment]
我很反感炒作，因为我对炒作的底层了如指掌。

**Comment by Geno1024** [comment]
我宣布战争开始。

**Comment by sakamoto-poteko** [comment]
先把pull request都结了吧

**Comment by 0532** [comment]
香烟 瓜子 火腿肠  。。。。。。

**Comment by muzea** [comment]
@sakamoto-poteko  如果把这个合并进去，那就是MingGeJS2.X的时代了
https://github.com/drduan/minggeJS/pull/92

**Comment by icymorn** [comment]
妈呀，这个逼没想到

**Comment by Tabjy** [comment]
火钳留名

**Comment by laike9m** [comment]
大戏啊，前排围观(´・ω・`)

**Comment by laike9m** [comment]
你要证明他是主谋很简单，发聊天截图就行，别说没有。

**Comment by linyuekai** [comment]
路过打酱油。。。
