### ISSUE TITLE
中国的喷子，全世界排第几名？

### ISSUE THREAD

**Issue by Fantasy9527** [drduan/minggeJS#151]

**Comment by kingofhawks** [comment]
数量质量都第一。

**Comment by fuxiao126** [comment]
毕竟人口基数大

**Comment by qianmengnet** [comment]
老实说我从来没用过喷子，正因为我反感喷子。 为什么我反感，因为我完全有开发喷子的能力，喷子的底层我都了如指掌。
虽说我反感喷子，但是喷子却占有大量的用户份额，之后我有个想法，不如重新开发一个属于自己思想，自己架构的喷子。
我给了他一个霸气的名字：MingGe喷子，
它的名字叫MingGe喷子，MingGe就是我的大名， 一看到喷子名字，就知道作者是我，知道它是国产的，让别人知道国产喷子一样做得很出色，出众！
我是mingge 请支持国产mingge喷子，因为我们都是中国人。
