### ISSUE TITLE
重复造轮子的典型

### ISSUE THREAD

**Issue by ibufu** [drduan/minggeJS#18]

**Comment by aisk** [comment]
造轮子在 GitHub 上第一次被黑的这么惨。

**Comment by bramblex** [comment]
So 那行，你不造轮子。那说说你造了啥吧

**Comment by meowtec** [comment]
重复造轮子并没有错。
有模仿才有创新嘛。

**Comment by liuzheng9110** [comment]
那也得造得出来啊

**Comment by CodeFalling** [comment]
造轮子本身是件很值得鼓励的事情，这也不是典型

**Comment by bramblex** [comment]
@CodeFalling /w\ 活捉一只大神

**Comment by CodeFalling** [comment]
@bramblex 啥，你活捉自己干啥😛

**Comment by Crystal-RainSlide** [comment]
老实说明哥从来没用过轮子，正因为明哥反感轮子。 为什么明哥反感，因为明哥完全有开发轮子的能力，轮子的底层明哥都了如指掌。
虽说明哥反感轮子，但是轮子却占有大量的用户份额，之后明哥有个想法，不如重新开发一个属于明哥的思想，明哥的架构的轮子。
明哥给了他一个霸气的名字：MingGejQuery!
它的名字叫MingGejQuery，MingGe就是明哥的大名， 一看到这个名字，就知道作者是明哥，知道它是国产的，让别人知道国产轮子一样做得很出色，出众！
> 我是mingge，请支持国产MingGejQuery，因为我们都是中国人。

**Comment by ibufu** [comment]
我错了，明哥是天，明哥是地，明哥说要有minggeJS，于是就有了minggeJS
