### ISSUE TITLE
这尼玛绝对不是中国人

### ISSUE THREAD

**Issue by mobi12** [drduan/minggeJS#182]
我们中国没有这么傻逼的人

**Comment by liu-zhe** [comment]
@mobi12 

老实说我从来没用过傻逼，正因为我反感傻逼。 为什么我反感，因为我完全有开发傻逼的能力，傻逼的底层我都了如指掌。

虽说我反感傻逼，但是傻逼却在测试界占有大量的用户份额，之后我有个想法，不如重新开发一个属于自己思想，自己架构的傻逼。

我给了他一个霸气的名字：MingGe傻逼，

它的名字叫MingGe傻逼，MingGe就是我的大名， 一看到傻逼名字，就知道作者是我，知道它是国产的，让别人知道国产傻逼一样做得很出色，出众

我是mingge 请支持国产mingge傻逼，因为我们都是中国人。
