### ISSUE TITLE
靡不有初，鲜克有终。献上我真诚的致歉，结束这场狂欢吧

### ISSUE THREAD

**Issue by justjavac** [drduan/minggeJS#186]
@minggeJS 
@drduan 

原文在知乎，太长了，就不贴到这里了

https://www.zhihu.com/question/38624564/answer/78295230

**Comment by kunl** [comment]
+1

**Comment by liu-zhe** [comment]
+2

**Comment by fly-in-sky** [comment]
+3

**Comment by ye-ming** [comment]
+4

**Comment by wang-gang** [comment]
+5

**Comment by kchum** [comment]
+ 6

**Comment by jinze** [comment]
+7

**Comment by yanwen** [comment]
＋8

**Comment by ljmacx** [comment]
+9

**Comment by 0rangeT1ger** [comment]
+10

**Comment by yang-ling** [comment]
默默地先去搜了下这句话的意思。

[“靡不有初，鲜克有终”这是《诗经》中的一句话。意思是说人们大都有一个良好的开端，但很少有人能够善始善终。](http://baike.baidu.com/view/245217.htm)

**Comment by justjavac** [comment]
@yang-ling 是这个意思。习大大也引用过这句话。

minggeJS 已经有一个好的开始了，mingge 已经把他开源了。如果我们一味的过来喷，那么就会不能善终了。

**Comment by iugo** [comment]
+12

**Comment by ARwMq9b6** [comment]
:boom: 王炸！

**Comment by ryerh** [comment]
+13

**Comment by jsthon** [comment]
“虽千万人 吾往矣”

明哥加油！

**Comment by chaodongyue** [comment]
justjavac 也来了,惊奇

**Comment by justjavac** [comment]
@chaodongyue 我带着诚意扑面而来了

**Comment by Geno1024** [comment]
😐+14

**Comment by mingge8888** [comment]
https://github.com/drduan/minggeJS/issues/222 PK JQ有图有真相
