### ISSUE TITLE
有实力说话狂,那是自信,没实力还狂那是无知的自大!

### ISSUE THREAD

**Issue by tabooc** [drduan/minggeJS#189]
## `jQuery`的整体架构你都还没出来,就已经陷入修改无尽的BUG中了,怎么体现对`jQuery`底层了如指掌?

做类似`jQuery`类库的人多了去了,一个个低调写代码,出来的作品也是真正能用到生产线的,推广也知道自己是站在前人的肩膀上才有现在,你的呢?
## 然而你写的不行,对`jQuery`都谈不上了解,更别说底层,就已经在吹牛逼的道路上走的越来越远了!

# 有实力说话狂,那是自信,没实力还狂那是无知的自大!

这n个issue里面,调侃的居多,开口骂人的只有你自己,然而围观者只当看个猴子而已.

**Comment by fly-in-sky** [comment]
还真是，别人都是来吐槽。就他自己，直接问候别人的长辈。

**Comment by fly-in-sky** [comment]
![image](https://cloud.githubusercontent.com/assets/4996063/11992009/9a36b01e-aa5b-11e5-943e-4c4fcc4b8b73.png)

500个star是什么概念啊？如果没有justjavac，你能过50个star就不错了。

**Comment by wang-gang** [comment]
justjavac应该有5000个star吧 :hand:

**Comment by wenzi0github** [comment]
说的很在理，但是这位所谓的明哥什么也不听，却在吹牛逼的道路上越走越远。曾经吹嘘的一个星期做出来的框架，已经用半个月在修复bug了，而且整体结构混乱，一点注释也没有
