### ISSUE TITLE
$('<div>') is not working

### ISSUE THREAD

**Issue by afanasy** [drduan/minggeJS#200]
It supposed to create a new element

**Comment by minggeJS** [comment]
I simplify the selector, do not want too many did not affect the efficiency of the regular! Unified use $("div")

**Comment by minggeJS** [comment]
I don't know English, it's online.

**Comment by afanasy** [comment]
No problem, but 
```js
$('div') //should select existing element
```
```js
$('<div>') //should create a new element
```
It's different syntax.
Good luck with your lib! I think Chinese developers can bring a new vision to the coding world.

**Comment by minggeJS** [comment]
MinggeJS does not have this interface, many are simplified, especially selector

Create element. Unified using the $(XXXX).CreateNode ()

**Comment by afanasy** [comment]
@minggeJS ok, thanks!

**Comment by bdbai** [comment]
Why did you take this so seriously? It's not a lib but a joke.

**Comment by momoNorthy** [comment]
yes,it is a lib, a chinese lib not mingge's own.today Chinese use jquery,we develop minggejs,next day,every one use minggejs! if you.really love china and

**Comment by momoNorthy** [comment]
you must  help mingge!
