### ISSUE TITLE
更新内容呢？

### ISSUE THREAD

**Issue by Cat7373** [drduan/minggeJS#207]
一直升级升级的，到底改了些啥？
直接删了旧文件上传新文件导致Github自带的文件对比功能没法用。
而你又不说改动了啥，那谁知道到底改了啥？
希望以后更新不要再删文件了，直接编辑已有文件即可。
以及详细的写出更新的内容来。

**Comment by minggeJS** [comment]
好的，臭妹纸，1.82版主要是修一些BUG，以及一些部份部份代码简化和优化等等

@Cat7373 我们可以从朋友做起吗，妹纸

**Comment by minggeJS** [comment]
@Cat7373 妹纸啊，好想你啊

**Comment by minggeJS** [comment]
@Cat7373 爱上你这种臭屁眼女孩子，我一无所有

**Comment by miuchan** [comment]
@Cat7373 明哥想你了，怎么还不出现呢？

**Comment by minggeJS** [comment]
@miuchan 挖开臭屁眼妹纸的屁眼进行疯狂舔食，舔屁眼，舔美女妹纸屁眼

**Comment by minggeJS** [comment]
舔了心爱女孩子的屁眼，虽然有点臭臭的，起码我喜欢舔，舔了臭又如何，起码我喜欢舔

**Comment by XadillaX** [comment]
@Cat7373 明哥你也敢质疑？

**Comment by rccoder** [comment]
@Cat7373  明哥好像被封了

**Comment by Cat7373** [comment]
@rccoder 
如果一个账号从不使用 Git 来提交代码，仅仅使用网页来做一些操作，甚至从不提交代码只是经常发 Issue 以及回复，那么很容易被认为是“机器人“，从而被封禁账号，所发布的代码、Issue、回复等均会被隐藏。
恢复则需要通过申请证明自己是个人。

**Comment by rccoder** [comment]
赞~

之前挺同情这人的，后面发现就是一个傻X

在 2016年1月2日 下午8:02，Cat73 <notifications@github.com>写道：

> @rccoder <https://github.com/rccoder>
> 如果一个账号从不使用 Git 来提交代码，仅仅使用网页来做一些操作，甚至从不提交代码只是经常发 Issue
> 以及回复，那么很容易被认为是“机器人“，从而被封禁账号，所发布的代码、Issue、回复等均会被隐藏。
> 恢复则需要通过申请证明自己是个人。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drduan/minggeJS/issues/207#issuecomment-168384199>.
>



-- 
-----

杨尚斌

哈尔滨工业大学

www.rccoder.net

**Comment by publicaaa** [comment]
@Cat7373  被封禁的原因是攻击性言论。 github 处理投诉的速度挺快的。

**Comment by Cat7373** [comment]
不知道Github还有投诉0.0

**Comment by mingge16888** [comment]
@Cat7373 臭屁眼妹子，你為什麼舉報我呢，能幫我解封嗎

**Comment by nibaozhu** [comment]
svn diff 可以查各版本代码改动

**Comment by Cat7373** [comment]
@nibaozhu
我是说这货直接删了旧版文件再上传新版文件，这样就不容易直接对比代码了。
再说能对比代码意义也不大，还需要提交者写清楚更新内容才能知道具体改动了什么。

**Comment by nibaozhu** [comment]
可以fork一个分支，然后自己写。
