### ISSUE TITLE
minggejs好像没什么关注度了，再发一个issues增加点人气

### ISSUE THREAD

**Issue by wenzi0github** [drduan/minggeJS#211]
我想问个问题，minggejs比jquery代码少，少了什么，jquery代码多，多又做了什么？minggerjs比jquery快，快在哪里？又是怎么提高效率的？

**Comment by mingge8888** [comment]
下载地址：http://pan.baidu.com/s/1qXoqtKo

PS:MingGeJS1.9.0升级：

寄语：很多人问我为什么源代码没有注释，我现在说给听，minggeJS不是给你看，更不是给你研究的，是用来给用户使用的，是用来应用大型项目的
是用来开发前端插件的。我再强调一次 源代码不是给你看的。这只是不写注释的原因之一，另一个原因是害怕别人偷我的技术，我写注释，方便 你偷技术吗
我本来不应该发源码出去的，应该只发布压缩版的。

MingGeJS1.9.0是过年前最大的一次更新:

1：事件绑定机制变更，性能进一步加强，全面支持事件委托-示例 $(xxx).on(event,"选择器"，function(){}); （这个变更我花费太多时间了）;

2: 新增$.bindFn.extend()事件API创建接口，用法和$.Fn.extend()一样,不同的是操作事件API接口而已，
事件接口创建后。可能通过$.bind("xxx",function) 可进行引用。

3：createNode 函数被喷严重，被迫全部重写，已与JQUERY对齐，别外 append 和insertBefore语法，参数方式等和JQUERY也一致，createNode保留中文参数传入

4：新增$.data接口操作，事件内存，动画内存等等统一通过$.data接口进行管理，

5： [attr="x"]修复选择器的BUG，增加对attr属性的IE678兼容与支持，以及准确度修复，选择器性能等，选择器的代码几乎百分之80以上重写了

6：修复[attr="x"]div attr在前div在后边时，选择器取不出的BUG

7: 新增移动端tap事件 doubleTap(双击) tap(单击)。后续会加入更手机事件

8: 新增$(XX).offset()（不带参数设置）

10：一如既往地各类函数的BUG，不再详述

11: 这次的升级应该是最大型的一次升级，终于达破2000行代码大关了，
新的一年希望更多用户加入minggeJS的大家庭,下一版将会加对AMD的支持，模块依赖加载等，请密切关注

12：下期版本提示：
全面继续加强手机事件接口，目前在山寨angularjs中，经过详细考虑，山寨angularjs的项目会与minggeJS进行整合，
也就是说DOM操作和MVVM架构操作都可以同时在minggeJS下进行，
山寨angularjs 会以精简版形式面向用户，目前代码在1200行左右，请继续关注

下载地址：http://pan.baidu.com/s/1qXoqtKo

**Comment by wenzi0github** [comment]
您不想让别人看到源码，何必放到github上；还有，mac下解压不了rar

**Comment by wenzi0github** [comment]
您的压缩版怎么不放到github上？

**Comment by JonneyYan** [comment]
@wenzi0github 大家都是来这repo玩的，别太认真
