### ISSUE TITLE
大家好，怎么取消 Github 贡献那栏的某一个库

### ISSUE THREAD

**Issue by fegg** [drduan/minggeJS#233]
＝＝我有代码洁癖。。。不想把这个 minggeJS 显示在我贡献库里面，谢谢～

**Comment by wenzi0github** [comment]
母鸡啊。可能你只写过issues，github也认为你做过贡献了。你把你在这个项目里写过所有的issues和所有回复过的，都删了。再看看

**Comment by mingge8888** [comment]
这句话有骨啊，你奈何不直接说我的代码是垃圾！而且你有一种看不 起别人的FEEL

minggejs1.9.6.2经过三个多月的重构工作，已经无可挑剔，在逻辑处理相同的情况下 比JQ还要快5倍，  Issues有一个测试贴，可以去看下。如果代码写得不好，逻辑写得不好，你是没有可能超越他的，因为JQ也很优秀，我负出很多大努力和汗水，我希望大家尊重一下别人的劳动成果

再说说第一个版本，minggejs1.6版本，这个版本是我开发一个星期就发布的版本，当时代码大概是1000行左右，网络随即出现很多对minggejs的负面评论。你要记住，是一个星期就发布的版本，你问你自己你一个星期能做过什么产品。我一个星期，我开发了一个失败的JQ，当时，代码里各种问题让我一夜之间名誉扫地。  minggejs1.9.6.2版本是我以往弥补一齐错误的版本，minggejs还没走完，只要我还在，minggejs一直会走下去，有一天我不在了，我的子子孙孙也会让minggejs走下去。

今天你笑我，明天别人笑你，懂得尊重别人的劳动成果，你问心无愧敢说自己的JS水比我高？


                                                

  --------------------JS PHP   易语言 DELPHI 高级总工程师 -明哥先生 上

**Comment by mingge8888** [comment]
@fegg         J S PHP 易语言 DELPHI 高级总工程师 -明哥先生 上

**Comment by mingge8888** [comment]
@wenzi0github  楼主的醉翁之意不在酒，是带着骨说，minggejs的代码是垃圾。

**Comment by mingge8888** [comment]
minggejs 目前有1万左右的用户，用户一致地肯定比JQ确实快很多，还有些客户用来开发APP应用，也有部份客户用来开发小型插件，感谢一直支持minggejs的用户。   但是有些人还是带着有色眼镜来蔑视别人劳动成果，开发一个星期就发布的minggejs1.6留下的污点，让我非常难过

**Comment by mingge8888** [comment]
![qq 20160328114615](https://cloud.githubusercontent.com/assets/16685857/14070551/b520325a-f4da-11e5-8807-7f6c523f9a9b.jpg)

**Comment by Naville** [comment]
还好我只留评论不开issues
--------垃圾iOS逆向工程师 暗弟小姐，上

**Comment by Naville** [comment]
哎哟这个issues的编号正好233
我真是233了

**Comment by Naville** [comment]
哦一个星期能做出什么。
@mingge8888 我一个星期写了个LLVM Pass : )

**Comment by DD-L** [comment]
233

**Comment by XadillaX** [comment]
有一个办法就是贡献更多的 repo。

来贡献我的吧😂

**Comment by MarkWh1te** [comment]
233 
火前刘明
