### ISSUE TITLE
管理一下你的版本号

### ISSUE THREAD

**Issue by wenzi0github** [drduan/minggeJS#241]
觉得你的版本号有点乱

![img](https://cloud.githubusercontent.com/assets/8475373/14701065/d34a5e6e-07d5-11e6-986f-a666ef53bd1f.png)

**Comment by mingge8888** [comment]
我喜欢用百度网盘，不喜欢github，github纯粹当网盘来用，

**Comment by wenzi0github** [comment]
@mingge8888 可是github传递的信息，明显比网盘多啊

**Comment by limeng0403** [comment]
指望明哥版的git是没指望了，不会用，怎么开发啊。

**Comment by MarkWh1te** [comment]
tree new bee?

**Comment by AkinoKaede** [comment]
老实说我从来没用过Git，正因为我反感Git。 为什么我反感，因为我完全有开发Git的能力，Git的底层我都了如指掌。
虽说我反感Git，但是Git却占有大量的用户份额，之后我有个想法，不如重新开发一个属于自己思想，自己架构的Git。
我给了他一个霸气的名字：MingGeGit，
它的名字叫MingGeGit，MingGe就是我的大名， 一看到Git名字，就知道作者是我，知道它是国产的，让别人知道国产Git一样做得很出色，出众！
我是mingge 请支持国产minggeGit，因为我们都是中国人。
