### ISSUE TITLE
你们忍心看着明哥悲惨的遭遇否【直接上图】

### ISSUE THREAD

**Issue by drduan** [drduan/minggeJS#246]
![mingg6](https://cloud.githubusercontent.com/assets/7875572/18421800/d6a6eb8a-78c4-11e6-9760-5e31aedeabf7.png)

**Comment by cometwo** [comment]
赶紧把这货送进精神病院

**Comment by jellykaiser** [comment]
瑟瑟发抖

**Comment by cw1997** [comment]
害怕
