### ISSUE TITLE
提几点建议

### ISSUE THREAD

**Issue by jiangtao** [drduan/minggeJS#35]
1. 建议支持模块化接入，比如commonjs, amd, cmd等支持
2. 建议提供不同版本语法支持，比如ES6等
3. 建议国际化。 请不要喷我。这里指的代码里面不要有中文的状态。

**Comment by meowtec** [comment]
用 commonjs / amd 做什么？请支持国产 CMD，因为我们都是中国人。

**Comment by justjavac** [comment]
请支持minggeLoader
