### ISSUE TITLE
明哥，我用不习惯github，都是英文，能不能换到国内的代码托管网站

### ISSUE THREAD

**Issue by xiongwei-git** [drduan/minggeJS#57]
https://gitcafe.com/
http://git.oschina.net/
到时候第一时间來粉你

**Comment by JasinYip** [comment]
补充个 http://git.coding.net （逃

**Comment by wenzi0github** [comment]
这不行，你托管到国内的网站，那怎么占据外国的份额呢

**Comment by EvilsoulM** [comment]
期待明哥出 gitMingGe~

**Comment by justjavac** [comment]
这不行，你托管到国内的网站，那怎么占据外国的份额呢 +1

**Comment by lincanbin** [comment]
这不行，你托管到国内的网站，那怎么占据外国的份额呢+2

**Comment by xzer** [comment]
这不行，你托管到国内的网站，那怎么占据外国的份额呢+3
