### ISSUE TITLE
明哥我爱你，爱明哥的进来

### ISSUE THREAD

**Issue by jiangyinbin** [drduan/minggeJS#61]
# 被楼主的才华所吸引！JQuery 定义了牛逼，而明哥定义了傻逼！我对明哥的敬仰如滔滔江水，绵绵不绝！明哥还缺打下手的吗，看门的那种！！！

**Comment by duanyikang** [comment]
silly

**Comment by JerryC8080** [comment]
## 听说有人叫我，明哥也爱你
![u 2828692215 3727933801 fm 21 gp 0](https://cloud.githubusercontent.com/assets/6801672/11804149/8a8c3196-a33c-11e5-9992-024f5df2ca59.jpg)
