### ISSUE TITLE
明哥这么早就说要超越JQUERY，会不会给人一种内定啊，钦点的感觉？

### ISSUE THREAD

**Issue by Foolyou** [drduan/minggeJS#74]
要不要按照基本法，按照GIT的法律？

**Comment by Hacker-YHJ** [comment]
6666666

**Comment by Hacker-YHJ** [comment]
你们码农千万要记着，不要“见得风，是得雨”。接到这个消息，你们码农本身也要判断，明白意思吗？假使这些完全无中生有的东西，你再帮他说一遍，你等于..你也有责任吧。

**Comment by 0rangeT1ger** [comment]
naive.

**Comment by Foolyou** [comment]
我有点担心在 GitHub 里发这个会不会引起什么不好的事情来......
