### ISSUE TITLE
是在下输了

### ISSUE THREAD

**Issue by sungerk** [drduan/minggeJS#83]
![Image of Yaktocat](http://imgsrc.baidu.com/forum/w=580/sign=7e16b7c0a1efce1bea2bc8c29f50f3e8/db23c43f8794a4c293e7131d08f41bd5ac6e396f.jpg)

**Comment by 2lei** [comment]
竟然上了trending

**Comment by ChenZhongPu** [comment]
Github已经被空间狗占领了

**Comment by sungerk** [comment]
mingge is really very fucking great
