### ISSUE TITLE
我与明哥二三事

### ISSUE THREAD

**Issue by fatrbaby** [drduan/minggeJS#86]
> 虽然我不认识明哥，但我和明哥一起经历过很多风风雨雨，一路上走得跌跌撞撞踉踉跄跄。摘几则记为《我与明哥二三事》。

to be continue……

**Comment by Zhangjd** [comment]
打错字, to be continued.

**Comment by muzea** [comment]
@Zhangjd  这是语法错误吧，毕竟MingGe不会英语
